server:
  port: 7002
eureka:
  instance:
    hostname: eureka-7002.com
  client:
    registerWithEureka: false #是否要注册到eureka
    fetchRegistry: false #表示是否从Eureka Server获取注册信息
    serviceUrl:
      #defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/#单机配置
      defaultZone: http://eureka-7001.com:7001/eureka/ #单机配置


