server:
  port: 9003
spring:
  application:
    name: USER-CONSUMER-FEIGN #不要使用下划线
eureka:
  client:
    registerWithEureka: true #不注册到Eureka,不在注册中心显示
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7002.com:7002/eureka
feign:
   hystrix:
       enabled: true
   client:
    config:
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 3000  #配置超时时间
        readTimeout: 3000
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000
ribbon:
  eureka:
    enabled: true
