server:
  port: 9003
spring:
  application:
    name: USER-CONSUMER-FEIGN #不要使用下划线
  zipkin:
    base-url: http://127.0.0.1:9411/
eureka:
  client:
    registerWithEureka: true #不注册到Eureka,不在注册中心显示
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7002/eureka