server:
  port: 8004
spring:
  application:
    name: USER-PROVIDER #不要使用下划线
eureka:
  client:
    service-url:
     #defaultZone: http://localhost:7001/eureka #告诉服务提供者要把服务注册到哪儿
     defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/ #告诉服务提供者要把服务注册到哪儿