server:
  port: 9002
spring:
  application:
    name: USER-CONSUMER-RIBBON #不要使用下划线
  cloud:
    loadbalancer:
      retry:
        enabled: true  #开启retry  启用重试机制
eureka:
  client:
    registerWithEureka: false #不注册到Eureka,不在注册中心显示
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7002.com:7002/eureka
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

USER-PROVIDER:
  ribbon:
#    ConnectTimeout: 250
#    ReadTimeout: 3000
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
custom:
  rest:
    connectionRequestTimeout: 250
    connectTimeout: 1000
    readTimeout: 3000